Bug Fixed
lightnovel-center/linovelib2epub pull request #14
Opened 2023-07-11 14:14 UTC by Holence

- 爬取图片的headers增添了'referer'
- 第一章（插圖）图片为lazyload，修改获取url为"data-src"属性
- 增添了去除第一章（插圖）多余图片的功能（很多图片是后续章节的黑白插图，没必要再次出现在第一章的彩图中）
- 修复了divide_volume=True时，所有每个epub都会存有所有图片的bug：在LightNovelVolume和volume dict中添加了一个volume_img_folder属性，将图片保存在`[image_download_folder]/[volume_img_folder]/[filename]`的路径
- 修改了book.toc的生成方法
    - divide_volume=False时，保持原先不变
    - divide_volume=True时，一级标题为volume里的所有chapter（一些阅读器可以显示 `当前chapter已读的页数 / 当前chapter的总页数`）

2023-07-11 16:32 UTC, wdpm requested changes
review了一下代码变更，部分地方希望可以改进下。

2023-07-11 16:32 UTC, wdpm commented on src/linovelib2epub/spider/linovelib_mobile_spider.py
> +
这里逻辑是img src的求解。优先处理lazyload的图片，然后是通常的src方式。没问题。

2023-07-11 16:32 UTC, wdpm commented on src/linovelib2epub/spider/linovelib_mobile_spider.py
> +                            replace_value = '<img src="' + f'{self.spider_settings["image_download_folder"]}/' + local_image_uri + '"/>'
这里的代码我认为有点激进了。因为原来网站的img标签可能是如下形式：
```html
<img class="imagecontent" src="images/w.linovelib.com/3-3610-182486-209181.jpg"/>
```
或者
```html
<img src="cover.jpg" alt="Cover"/>
```
等等。这里img可能存在class属性或者alt属性，这些属性是有可能成为CSS选择器来美化样式的，而且这些属性的存在，使得可以区分哪些是封面，哪些是一般的插图。

这里的代码暴力地去掉了img的其他属性，只保留src属性，我认为不合理。
这里应该使用之前的方式，精准捕获src，仅替代src即可。

2023-07-11 16:32 UTC, wdpm commented on src/linovelib2epub/spider/linovelib_mobile_spider.py
> +                def removeInList(match, l):
pythonic命名风格下，似乎不太喜欢java风格的小驼峰来命名function。而且，这个函数`def removeInList(match, l):`并没有remove操作，语义不够直白。例如，可以考虑 filter_duplicate_images这种命名方式

2023-07-11 16:32 UTC, wdpm commented on src/linovelib2epub/spider/linovelib_mobile_spider.py
> +                        return s
这里排版似乎有点紧密，可以利用一个空行将它们视觉上进行逻辑隔开。

2023-07-11 16:32 UTC, wdpm commented on src/linovelib2epub/spider/linovelib_mobile_spider.py
> +                chapter_list[0].content=re.sub('<img src=".*?"/>', lambda m: removeInList(m, check_img_duplicate_list), chapter_list[0].content)
这里是仅对第一个章节进行处理，将第一个章节的重复图片去掉，看起来代码没问题。

2023-07-11 16:36 UTC, wdpm commented
> 1. 爬取图片的headers增添了'referer'
> 2. 第一章（插圖）图片为lazyload，修改获取url为"data-src"属性
> 3. 增添了去除第一章（插圖）多余图片的功能（很多图片是后续章节的黑白插图，没必要再次出现在第一章的彩图中）
> 4. 修复了divide_volume=True时，所有每个epub都会存有所有图片的bug：在LightNovelVolume和volume dict中添加了一个volume_img_folder属性，将图片保存在`[image_download_folder]/[volume_img_folder]/[filename]`的路径
> 5. 修改了book.toc的生成方法
>    
>    * divide_volume=False时，保持原先不变
>    * divide_volume=True时，一级标题为volume里的所有chapter（一些阅读器可以显示 `当前chapter已读的页数 / 当前chapter的总页数`）

4,5点明天再看，太晚了。

2023-07-12 06:05 UTC, wdpm requested changes
部分地方需要修改，修改建议在review中已经给出。

2023-07-12 06:05 UTC, wdpm commented on src/linovelib2epub/spider/linovelib_mobile_spider.py
> +                )
看起来没啥问题

2023-07-12 06:14 UTC, wdpm reviewed
第3个commit没问题。同意

2023-07-12 06:14 UTC, wdpm approved these changes

2023-07-12 06:22 UTC, Holence commented on src/linovelib2epub/spider/base_spider.py
> +            os.makedirs(os.path.dirname(save_path))
`os.path.dirname`会计算出最深层的文件夹，实际是在做`os.makedirs('image_download_folder/volume_img_folder')`

2023-07-12 06:25 UTC, wdpm commented on src/linovelib2epub/spider/base_spider.py
> +            os.makedirs(os.path.dirname(save_path))
你的逻辑是对的，是我的失误。

2023-07-12 06:26 UTC, Holence commented on src/linovelib2epub/spider/linovelib_mobile_spider.py
> +                            replace_value = '<img src="' + f'{self.spider_settings["image_download_folder"]}/' + local_image_uri + '"/>'
已在commit 4中修改

2023-07-12 07:38 UTC, wdpm requested changes
等待其他的变更

2023-07-12 12:50 UTC, Holence commented on src/linovelib2epub/spider/base_spider.py
> +    def request_headers(self, referer: str = '', random_ua: bool = True) -> dict:
所以是在`_download_image_legacy`和`_download_image`中手动传入header吗

2023-07-12 13:08 UTC, wdpm commented on src/linovelib2epub/spider/base_spider.py
> +    def request_headers(self, referer: str = '', random_ua: bool = True) -> dict:
> 所以是在`_download_image_legacy`和`_download_image`中手动传入header吗

不是，我的意思是base类不应该实现过于具体的headers，保持返回｛｝就好。
具体headers的设置应该交给子类来具体化，也就是linovelib_mobile_spider.py来覆盖。这也是之前的行为。
利用多态的特性，子类在实际下载图片时，例如：
```
async with session.get(url, headers=self.request_headers(), timeout=timeout) as resp:
```
这里的self.request_headers()的利用的正是子类具体的实现，而不是父类（base类）的默认实现。

2023-07-12 13:11 UTC, wdpm commented on src/linovelib2epub/spider/base_spider.py
> +    def request_headers(self, referer: str = '', random_ua: bool = True) -> dict:
我本地构造一个简单的例子，等会发出来，这样比较容易讨论。

2023-07-12 13:16 UTC, wdpm commented on src/linovelib2epub/spider/base_spider.py
> +    def request_headers(self, referer: str = '', random_ua: bool = True) -> dict:
```
class BaseFoo:
    def get_headers(self) -> dict:
        return {}

    # 这是一个父类的普通方法，使用了get_headers()
    def method_a(self):
        print(self.get_headers())


class ConcreteFoo(BaseFoo):

    # 子类覆盖父类对应方法，给出具体的子类实现
    def get_headers(self) -> dict:
        return {"name": "ConcreteFoo"}


foo = ConcreteFoo()
print(foo.method_a())
# {'name': 'ConcreteFoo'}

# method_a实际上借用了父类的方法定义method_a，里面的self.get_headers() 实际上却使用了子类的get_headers(self)实现
# 这就是OOP多态的体现。

```

2023-07-12 13:16 UTC, wdpm commented on src/linovelib2epub/spider/base_spider.py
> +    def request_headers(self, referer: str = '', random_ua: bool = True) -> dict:
@Holence

2023-07-12 13:45 UTC, Holence commented on src/linovelib2epub/spider/base_spider.py
> +    def request_headers(self, referer: str = '', random_ua: bool = True) -> dict:
感谢详细的解答！自己多态用的少了😓

2023-07-12 13:51 UTC, Holence commented on src/linovelib2epub/linovel.py
> +                if volume["volume_img_folder"]:
已修正

2023-07-12 14:14 UTC, wdpm approved these changes

2023-07-12 14:19 UTC, merged

2023-07-12 14:20 UTC, wdpm commented
@all-contributors please add @Holence  as a contributor for code

2023-07-12 14:36 UTC, wdpm commented
@Holence 辛苦了，感谢你的代码贡献。

2023-07-12 14:45 UTC, Holence commented
没事，也是自己需要用，就顺便修了修😄